// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// website.js
export const SET_WEBSITE = 'SET_WEBSITE'
export const FETCH_ALL_WEBSITE = 'FETCH_ALL_WEBSITE'
export const SAVE_WEBSITE = 'SAVE_WEBSITE'
export const DELETE_WEBSITE = 'DELETE_WEBSITE'

// website-post.js
export const SET_WEBSITE_POST = 'SET_WEBSITE_POST'
export const FETCH_ALL_WEBSITE_POST = 'FETCH_ALL_WEBSITE_POST'
export const SAVE_WEBSITE_POST = 'SAVE_WEBSITE_POST'
export const DELETE_WEBSITE_POST = 'DELETE_WEBSITE_POST'

// website-subscriber.js
export const FETCH_ALL_WEBSITE_SUBSCRIBER = 'FETCH_ALL_WEBSITE_SUBSCRIBER'
export const SUBSCRIBE_TO_WEBSITE = 'SUBSCRIBE_TO_WEBSITE'
export const UNSUBSCRIBE_TO_WEBSITE = 'UNSUBSCRIBE_TO_WEBSITE'
export const FETCH_USER_WEBSITES = 'FETCH_USER_WEBSITES'
